apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: test
  labels:
    app: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server-ctr
        image: felipecruz/go-server
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-server
  namespace: test
  labels:
    app.kubernetes.io/name: loadtester
    app.kubernetes.io/instance: flagger  
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: go-server
---          